import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const blogsDir = path.join(projectRoot, "public/content/blogs");
const outputFile = path.join(projectRoot, "src/data/local-blogs.generated.ts");

const parseFrontmatter = (content) => {
  // Regex to extract YAML block between --- lines at the beginning of the file
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) return { frontmatter: {}, body: content };

  const fmText = match[1];
  const body = match[2];
  const frontmatter = {};

  // Simple key-value parser for basic YAML frontmatter
  const lines = fmText.split("\n");
  for (const line of lines) {
    const colonIndex = line.indexOf(":");
    if (colonIndex === -1) continue;

    const key = line.slice(0, colonIndex).trim();
    let val = line.slice(colonIndex + 1).trim();

    // Clean strings (remove quotes)
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }

    // Parse array if value is like [a, b, c] or ["a", "b"]
    if (val.startsWith("[") && val.endsWith("]")) {
      try {
        const cleanVal = val.replace(/'/g, '"');
        frontmatter[key] = JSON.parse(cleanVal);
      } catch (e) {
        frontmatter[key] = val.slice(1, -1).split(",").map(s => s.trim().replace(/^["']|["']$/g, ""));
      }
    } else {
      frontmatter[key] = val;
    }
  }

  return { frontmatter, body };
};

const main = async () => {
  await mkdir(blogsDir, { recursive: true });
  await mkdir(path.dirname(outputFile), { recursive: true });

  const files = await readdir(blogsDir);
  const mdFiles = files.filter(f => f.endsWith(".md"));

  const localBlogs = [];

  for (const file of mdFiles) {
    const filePath = path.join(blogsDir, file);
    const content = await readFile(filePath, "utf8");
    const { frontmatter } = parseFrontmatter(content);
    const slug = path.basename(file, ".md");

    // Format the date to look like "Jun 13, 2026"
    let displayDate = "";
    let isoDate = "";
    
    if (frontmatter.date) {
      const parsedDate = new Date(frontmatter.date);
      if (!Number.isNaN(parsedDate.getTime())) {
        displayDate = parsedDate.toLocaleDateString("en-US", {
          year: "numeric",
          month: "short",
          day: "numeric",
        });
        isoDate = parsedDate.toISOString();
      }
    }

    if (!displayDate) {
      const now = new Date();
      displayDate = now.toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
      });
      isoDate = now.toISOString();
    }

    localBlogs.push({
      title: frontmatter.title || slug,
      source: "local",
      sourceLabel: "Blog Post",
      date: displayDate,
      isoDate: isoDate,
      description: frontmatter.description || "",
      tags: frontmatter.tags || [],
      link: `/blog/${slug}`,
      slug,
      image: frontmatter.image || "",
    });
  }

  // Sort by date descending
  localBlogs.sort((a, b) => b.isoDate.localeCompare(a.isoDate));

  const code = `// This file is auto-generated by scripts/sync-blogs.mjs. Do not edit directly.
import { ArticleItem } from "./articles.generated";

export interface LocalBlogItem extends ArticleItem {
  slug: string;
}

export const localBlogs: LocalBlogItem[] = ${JSON.stringify(localBlogs, null, 2)};
`;

  await writeFile(outputFile, code, "utf8");
  console.log(`Generated ${localBlogs.length} local blogs to src/data/local-blogs.generated.ts`);
};

main().catch(err => {
  console.error(err);
  process.exitCode = 1;
});
