// This file is auto-generated by scripts/sync-blogs.mjs. Do not edit directly.
import { ArticleItem } from "./articles.generated";

export interface LocalBlogItem extends ArticleItem {
  slug: string;
}

export const localBlogs: LocalBlogItem[] = [
  {
    "title": "Service Registry, Kubernetes Service Discovery, API Gateway, and Service Mesh — End-to-End Guide",
    "source": "local",
    "sourceLabel": "Blog Post",
    "date": "Jun 13, 2026",
    "isoDate": "2026-06-13T00:00:00.000Z",
    "description": "Understand how microservices find and call each other, when Eureka-style service registry works, and when tools like Istio are worth adding.",
    "tags": [
      "Kubernetes",
      "Service Mesh",
      "API Gateway",
      "Eureka"
    ],
    "link": "/blog/service-registry-service-mesh-kubernetes-blog",
    "slug": "service-registry-service-mesh-kubernetes-blog",
    "image": ""
  }
];
